# website name; shown in page title and copyright
name: 42bytes/Timber
logo: Timber

# meta tag information
author: Graeme Russell
description: An open-source Jekyll theme provided by 42bytes.com

# optional path to favicon
favicon: 
 
# how many (if any) share options to show at bottom of post (max 12)
# the share links shown are based on what AddThis assess to be the most
# likely for a particulr user to set
share_count: 6
addthis_username: 

# turn on and off tag display at the bottom of a post
show_tags: true

# how many (if any) related entries to show at bottom of post
related_count: 3

# turn on and off elsewhere links in header
elsewhere_email: contact <strong>at</strong> your_site.com
elsewhere_dribbble: http://www.dribbble.com
elsewhere_github: https://github.com/bytes42/timber
elsewhere_linkedin:
elsewhere_meetup: http://www.meetup.com
elsewhere_spotify: http://www.spotify.com
elsewhere_twitter: http://www.twitter.com
elsewhere_rss: http://www.feedburner.com

# standard Jekyll options
baseurl: /timber
exclude: ["README.md", "Rakefile", "404.haml", "index.haml", "tags.haml", "css/stylesheet.sass", "css/override.sass"]
permalink: pretty
pygments: true
safe: false
